name: Download and patch
env:
  GAME_XAPK_LINK: "https://d.apkpure.com/b/XAPK/com.bandainamcoent.idolmaster_gakuen?version=latest"
  USER_AGENT: "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:

permissions:
  contents: write
  
jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0        
    - name: Get latest tag and compare with existing
      run: |
          bash ver_check.sh
    - name: Download and prepare modules
      run: |
          bash download_modules.sh
          
    - name: Set up JRE 21
      uses: actions/setup-java@v4.6.0
      with:
          distribution: "zulu"
          java-version: "21"
          java-package: "jre"  
    - name: Prepare cloned APK file
      run: |
        bash clone.sh
    - name: Patch the APK files
      run: |
        bash patch.sh
        
    - name: Create a Release
      uses: softprops/action-gh-release@v2
      with:
        body: "### Gaku ${{ env.APK_VERSION }} ready to update.\nThe '_embedded' and 'cloned' apk require a new version of Localify to function.\nTo use them, download the included 'Localify.apk' if you did not already. \n**Other Localify versions will NOT work.**"
        tag_name: ${{ env.APK_VERSION }} 
        make_latest: true
        files: |
          ${{ env.EMBED_APK }}
          ${{ env.EMBED_APK_CLONED }}
          ${{ env.EMBED_APK_CN }}
          ${{ env.LOCALIFY_EN_NAME }}
          ${{ env.PATCHED_APK }}
      
        
    
