name: Download and patch-test

env:
  XAPK_LINK: "https://d.apkpure.com/b/XAPK/com.bandainamcoent.idolmaster_gakuen?version=latest"
  USER_AGENT: "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0"
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:

permissions:
  contents: write
  
jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    - name: Get latest tag and compare with existing
      run: |
          bash ver_check.sh
    
          
      
        
    
