name: Download and patch-test

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:

permissions:
  contents: write
  
jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    - name: Get latest tag and compare with existing
      run: |
          wget -q -S -U "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0" --start-pos 999999999999 https://d.apkpure.com/b/XAPK/com.bandainamcoent.idolmaster_gakuen?version=latest -O /dev/null
          
      
        
    
