name: Download and patch

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
  push:

permissions:
  contents: write
  
jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Get latest tag and compare with existing
      run: |
          bash ver_check.sh
          
    - name: Set up JRE 21
      uses: actions/setup-java@v4.6.0
      with:
          distribution: "zulu"
          java-version: "21"
          java-package: "jre"  
          
    - name: Download and patch
      run: |
        bash patch.sh
        
    - name: Create a Release
      uses: softprops/action-gh-release@v2
      with:
        body: "Gaku ${{ env.APK_VERSION }} ready to update."
        tag_name: ${{ env.APK_VERSION }} 
        make_latest: true
        files: ${{ env.PATCHED_APK }}
      
        
    
